Update anchorectl.yaml

diff --git a/.github/workflows/anchorectl.yaml b/.github/workflows/anchorectl.yaml
--- a/.github/workflows/anchorectl.yaml
+++ b/.github/workflows/anchorectl.yaml
@@ -21,7 +21,7 @@ on:
         
 jobs:
 
-  Build-Scan-Promote:
+  Build-Push:
     runs-on: ubuntu-latest
     env:
       ANCHORECTL_ANCHORE_USER: ${{ secrets.ANCHORECTL_ANCHORE_USER }}
@@ -42,7 +42,7 @@ jobs:
       
     - name: Build Docker Image
       run: |
-        docker build . --file Dockerfile --tag ${IMAGE_SHA}      
+        docker build . --file Dockerfile --tag ${IMAGE}      
                 
     - name: Install CLI Tools
       run: |
@@ -54,74 +54,16 @@ jobs:
                 
     - name: Generate SBOM 
       run: |
-        syft -o spdx-json docker:${IMAGE_SHA} > sbom.spdx.json
-        syft -o cyclonedx-json docker:${IMAGE_SHA} > sbom.cdx.json
-        
-    - name: Verify Anchore Ready and Reachable
-      run: |
-        anchorectl system wait --timeout 10
-        anchorectl system status
-        
-    - name: Push to SBOM Anchore
-      run: |
-        anchorectl sbom upload --overwrite --wait --dockerfile ./Dockerfile ${IMAGE_SHA}
-        
-    ### this isn't really necessary, some people want to archive this stuff
-    - name: Pull Vulnerability List
-      run: |
-        anchorectl image vuln ${IMAGE_SHA} all | tee anchore-vuln.txt
-    
-    ### pulling policy evaluation is not implemented in anchorectl as of v0.2.0 but will be in 
-    ### the next release via "anchorectl image check ${IMAGE}"
-    ### if you need this functionality now, here's how to do it with anchore-cli
-    #- name: Install anchore-cli
-    #  run: |
-    #    sudo apt-get install python3-pip
-    #    pip install anchorecli
-    #    export PATH="$HOME/.local/bin/:$PATH"
-    #- name: Pull Policy Evaluation
-    #  run: |
-    #    set -o pipefail
-    #    # we have to set pipefail so that we can still gate on the evaluation, otherwise piping into tee will mask the failure
-    #    # also note that for this step we use anchore-cli, anchorectl doesn't yet have "evaluate check" implemented as of 0.2.0
-    #    anchore-cli evaluate check --detail ${IMAGE_SHA} | tee anchore-policy.txt
-
-    - name: Re-Tag Image
-      run: |
-        docker tag ${IMAGE_SHA} ${IMAGE}
+        syft -o spdx-json docker:${IMAGE} > sbom.spdx.json
+        syft -o cyclonedx-json docker:${IMAGE} > sbom.cdx.json
+                
     - name: Login to ghcr.io
       run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${GITHUB_ACTOR} --password-stdin
       
     - name: Push Docker Image
       run: |
         docker push ${IMAGE}
-        
-    - name: Add Promoted Image to Anchore Queue
-      run: |
-        anchorectl image add --noautosubscribe ${IMAGE}
-        ### image wait isn't really necessary
-        #anchorectl image wait ${IMAGE}
-    ### if you want to clean up, you need anchore-cli for now since subscription operations are 
-    ### also not implemented in anchorectl yet as of v0.2.0
-    #- name: Purge Unneeded Evaluation
-    #  run: |
-    #    anchore-cli subscription list --full | grep ${GITHUB_SHA} | awk '{print $4}' | xargs -n 1 anchore-cli subscription del
-    #    anchorectl image delete ${IMAGE_SHA}
-    
-    ## optional, if you want continuous re-evaluations
-    ## still need anchore-cli for subscription operations
-    #- name: Activate Subscriptions
-    #    anchore-cli subscription activate policy_eval ${IMAGE}
-    #    anchore-cli subscription activate vuln_update ${IMAGE}    
-        
-    - name: Archive Vulnerabilities and Evaluation
-      if: always()
-      uses: actions/upload-artifact@v2
-      with:
-        name: evaluation-report
-        path: anchore-*.txt
-        retention-days: 14
-        
+                
     - name: Archive SPDX
       if: always()
       uses: actions/upload-artifact@v2
@@ -137,4 +79,71 @@ jobs:
         name: cdx-sbom
         path: sbom.cdx.json
         retention-days: 14
+
+
+  Scan-Analyze:
+    needs: Build-Push  
+    runs-on: ubuntu-latest
+    env:
+      ANCHORECTL_ANCHORE_USER: ${{ secrets.ANCHORECTL_ANCHORE_USER }}
+      ANCHORECTL_ANCHORE_PASSWORD: ${{ secrets.ANCHORECTL_ANCHORE_PASSWORD }}
+      ANCHORECTL_ANCHORE_URL: ${{ secrets.ANCHORECTL_ANCHORE_URL }}
+      IMAGE_REGISTRY: ghcr.io
+    steps:
+
+    - name: Checkout Code
+      uses: actions/checkout@v2
+                      
+    - name: Install CLI Tools
+      run: |
+        mkdir -p $HOME/.local/bin
+        curl https://anchorectl-releases.s3-us-west-2.amazonaws.com/v0.2.0/anchorectl_0.2.0_linux_amd64.tar.gz | tar xzvf - -C $HOME/.local/bin/
+        chmod 0755 $HOME/.local/bin/anchorectl
+        export PATH="$HOME/.local/bin/:$PATH"
+        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
+
+    - name: Verify Anchore Ready and Reachable
+      run: |
+        anchorectl system wait --timeout 10
+        anchorectl system status
+        
+    - name: Push to SBOM Anchore
+      run: |
+        anchorectl image add --force --noautosubscribe --annotations builder=github --dockerfile ./Dockerfile ${IMAGE}
+        anchorectl image wait ${IMAGE}
+
+    ### this isn't really necessary, some people want to archive this stuff
+    - name: Pull Vulnerability List
+      run: |
+        anchorectl image vuln ${IMAGE_SHA} all | tee anchore-vuln.txt
+        
+    ### pulling policy evaluation is not implemented in anchorectl as of v0.2.0 but will be in 
+    ### the next release via "anchorectl image check ${IMAGE}"
+    ### if you need this functionality now, here's how to do it with anchore-cli
+    #- name: Install anchore-cli
+    #  run: |
+    #    sudo apt-get install python3-pip
+    #    pip install anchorecli
+    #    export PATH="$HOME/.local/bin/:$PATH"
+    #- name: Pull Policy Evaluation
+    #  run: |
+    #    set -o pipefail
+    #    # we have to set pipefail so that we can still gate on the evaluation, otherwise piping into tee will mask the failure
+    #    # also note that for this step we use anchore-cli, anchorectl doesn't yet have "evaluate check" implemented as of 0.2.0
+    #    anchore-cli evaluate check --detail ${IMAGE_SHA} | tee anchore-policy.txt
+    #
+    ### optional, if you want continuous re-evaluations
+    ### still need anchore-cli for subscription operations (not yet in anchorectl 0.2.0)
+    #- name: Activate Subscriptions
+    #    anchore-cli subscription activate policy_eval ${IMAGE}
+    #    anchore-cli subscription activate vuln_update ${IMAGE}    
+    
+    - name: Archive Vulnerabilities and Evaluation
+      if: always()
+      uses: actions/upload-artifact@v2
+      with:
+        name: evaluation-report
+        path: anchore-*.txt
+        retention-days: 14
+
 
